// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Instant,
    InstantFromJSON,
    InstantToJSON,
} from './index';

/**
 * Вариант ответа
 * @export
 * @interface Choice
 */
export interface Choice  {
    /**
     * Уникальный идентификатор
     * @type {string}
     * @memberof Choice
     */
    id?: string;
    /**
     * Название варианта ответа
     * @type {string}
     * @memberof Choice
     */
    name?: string;
    /**
     * Значение варианта ответа
     * @type {number}
     * @memberof Choice
     */
    value?: number;
    /**
     * 
     * @type {Instant}
     * @memberof Choice
     */
    createdTime?: Instant;
}

export function ChoiceFromJSON(json: any): Choice {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'createdTime': !exists(json, 'createdTime') ? undefined : InstantFromJSON(json['createdTime']),
    };
}

export function ChoiceToJSON(value?: Choice): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'value': value.value,
        'createdTime': InstantToJSON(value.createdTime),
    };
}


