// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Практика
 * @export
 * @interface Department
 */
export interface Department  {
    /**
     * Уникальный идентикафикатор
     * @type {string}
     * @memberof Department
     */
    id: string;
    /**
     * Название
     * @type {string}
     * @memberof Department
     */
    name: string;
}

export function DepartmentFromJSON(json: any): Department {
    return {
        'id': json['id'],
        'name': json['name'],
    };
}

export function DepartmentToJSON(value?: Department): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
    };
}


