// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Запись справочника
 * @export
 * @interface DictionaryItem
 */
export interface DictionaryItem  {
    /**
     * Идентификатор записи
     * @type {number}
     * @memberof DictionaryItem
     */
    id?: number;
    /**
     * Код записи
     * @type {string}
     * @memberof DictionaryItem
     */
    code?: string;
    /**
     * Наименование записи
     * @type {string}
     * @memberof DictionaryItem
     */
    name?: string;
    /**
     * Описание записи
     * @type {string}
     * @memberof DictionaryItem
     */
    description?: string;
}

export function DictionaryItemFromJSON(json: any): DictionaryItem {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function DictionaryItemToJSON(value?: DictionaryItem): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'description': value.description,
    };
}


