// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Instant,
    InstantFromJSON,
    InstantToJSON,
} from './index';

/**
 * Событие
 * @export
 * @interface Event
 */
export interface Event  {
    /**
     * Уникальный идентификатор
     * @type {string}
     * @memberof Event
     */
    id?: string;
    /**
     * Уровень
     * @type {string}
     * @memberof Event
     */
    level?: string;
    /**
     * Источник
     * @type {string}
     * @memberof Event
     */
    source?: string;
    /**
     * Сообщение
     * @type {string}
     * @memberof Event
     */
    message?: string;
    /**
     * 
     * @type {Instant}
     * @memberof Event
     */
    createdTime?: Instant;
}

export function EventFromJSON(json: any): Event {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'level': !exists(json, 'level') ? undefined : json['level'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'createdTime': !exists(json, 'createdTime') ? undefined : InstantFromJSON(json['createdTime']),
    };
}

export function EventToJSON(value?: Event): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'level': value.level,
        'source': value.source,
        'message': value.message,
        'createdTime': InstantToJSON(value.createdTime),
    };
}


