// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FileImport,
    FileImportFromJSON,
    FileImportToJSON,
    Meta,
    MetaFromJSON,
    MetaToJSON,
} from './index';

/**
 * Список файлов
 * @export
 * @interface FileImportsList
 */
export interface FileImportsList  {
    /**
     * 
     * @type {Meta}
     * @memberof FileImportsList
     */
    meta?: Meta;
    /**
     * Результат
     * @type {Array<FileImport>}
     * @memberof FileImportsList
     */
    data?: Array<FileImport>;
}

export function FileImportsListFromJSON(json: any): FileImportsList {
    return {
        'meta': !exists(json, 'meta') ? undefined : MetaFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(FileImportFromJSON),
    };
}

export function FileImportsListToJSON(value?: FileImportsList): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'meta': MetaToJSON(value.meta),
        'data': value.data === undefined ? undefined : (value.data as Array<any>).map(FileImportToJSON),
    };
}


