// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Доступ к папке
 * @export
 * @interface FolderPermission
 */
export interface FolderPermission  {
    /**
     * Идентификатор папки
     * @type {string}
     * @memberof FolderPermission
     */
    folderId?: string;
    /**
     * Идентификатор пользователя
     * @type {string}
     * @memberof FolderPermission
     */
    objectSid?: string;
    /**
     * Название
     * @type {string}
     * @memberof FolderPermission
     */
    name?: string;
    /**
     * Права доступа
     * @type {number}
     * @memberof FolderPermission
     */
    permission?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FolderPermission
     */
    inheritance?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FolderPermission
     */
    group?: boolean;
}

export function FolderPermissionFromJSON(json: any): FolderPermission {
    return {
        'folderId': !exists(json, 'folderId') ? undefined : json['folderId'],
        'objectSid': !exists(json, 'objectSid') ? undefined : json['objectSid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'permission': !exists(json, 'permission') ? undefined : json['permission'],
        'inheritance': !exists(json, 'inheritance') ? undefined : json['inheritance'],
        'group': !exists(json, 'group') ? undefined : json['group'],
    };
}

export function FolderPermissionToJSON(value?: FolderPermission): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'folderId': value.folderId,
        'objectSid': value.objectSid,
        'name': value.name,
        'permission': value.permission,
        'inheritance': value.inheritance,
        'group': value.group,
    };
}


