// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Form,
    FormFromJSON,
    FormToJSON,
    Meta,
    MetaFromJSON,
    MetaToJSON,
} from './index';

/**
 * Список анкет
 * @export
 * @interface FormsList
 */
export interface FormsList  {
    /**
     * 
     * @type {Meta}
     * @memberof FormsList
     */
    meta?: Meta;
    /**
     * Результат
     * @type {Array<Form>}
     * @memberof FormsList
     */
    data?: Array<Form>;
}

export function FormsListFromJSON(json: any): FormsList {
    return {
        'meta': !exists(json, 'meta') ? undefined : MetaFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(FormFromJSON),
    };
}

export function FormsListToJSON(value?: FormsList): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'meta': MetaToJSON(value.meta),
        'data': value.data === undefined ? undefined : (value.data as Array<any>).map(FormToJSON),
    };
}


