// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrantedAuthority
 */
export interface GrantedAuthority  {
    /**
     * 
     * @type {string}
     * @memberof GrantedAuthority
     */
    authority?: string;
}

export function GrantedAuthorityFromJSON(json: any): GrantedAuthority {
    return {
        'authority': !exists(json, 'authority') ? undefined : json['authority'],
    };
}

export function GrantedAuthorityToJSON(value?: GrantedAuthority): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'authority': value.authority,
    };
}


