// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Дата и время создания
 * @export
 * @interface Instant
 */
export interface Instant  {
    /**
     * 
     * @type {Date}
     * @memberof Instant
     */
    value$kotlinxDatetime?: Date;
    /**
     * 
     * @type {number}
     * @memberof Instant
     */
    nanosecondsOfSecond?: number;
    /**
     * 
     * @type {number}
     * @memberof Instant
     */
    epochSeconds?: number;
}

export function InstantFromJSON(json: any): Instant {
    return {
        'value$kotlinxDatetime': !exists(json, 'value$kotlinx_datetime') ? undefined : new Date(json['value$kotlinx_datetime']),
        'nanosecondsOfSecond': !exists(json, 'nanosecondsOfSecond') ? undefined : json['nanosecondsOfSecond'],
        'epochSeconds': !exists(json, 'epochSeconds') ? undefined : json['epochSeconds'],
    };
}

export function InstantToJSON(value?: Instant): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'value$kotlinx_datetime': value.value$kotlinxDatetime === undefined ? undefined : value.value$kotlinxDatetime.toISOString(),
        'nanosecondsOfSecond': value.nanosecondsOfSecond,
        'epochSeconds': value.epochSeconds,
    };
}


