// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Дата архивации исследовательского проекта
 * @export
 * @interface LocalDate
 */
export interface LocalDate  {
    /**
     * 
     * @type {Date}
     * @memberof LocalDate
     */
    value$kotlinxDatetime?: Date;
    /**
     * 
     * @type {number}
     * @memberof LocalDate
     */
    monthNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof LocalDate
     */
    month?: LocalDateMonthEnum;
    /**
     * 
     * @type {string}
     * @memberof LocalDate
     */
    dayOfWeek?: LocalDateDayOfWeekEnum;
    /**
     * 
     * @type {number}
     * @memberof LocalDate
     */
    dayOfYear?: number;
    /**
     * 
     * @type {number}
     * @memberof LocalDate
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof LocalDate
     */
    dayOfMonth?: number;
}

export function LocalDateFromJSON(json: any): LocalDate {
    return {
        'value$kotlinxDatetime': !exists(json, 'value$kotlinx_datetime') ? undefined : new Date(json['value$kotlinx_datetime']),
        'monthNumber': !exists(json, 'monthNumber') ? undefined : json['monthNumber'],
        'month': !exists(json, 'month') ? undefined : json['month'],
        'dayOfWeek': !exists(json, 'dayOfWeek') ? undefined : json['dayOfWeek'],
        'dayOfYear': !exists(json, 'dayOfYear') ? undefined : json['dayOfYear'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'dayOfMonth': !exists(json, 'dayOfMonth') ? undefined : json['dayOfMonth'],
    };
}

export function LocalDateToJSON(value?: LocalDate): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'value$kotlinx_datetime': value.value$kotlinxDatetime === undefined ? undefined : value.value$kotlinxDatetime.toISOString().substr(0,10),
        'monthNumber': value.monthNumber,
        'month': value.month,
        'dayOfWeek': value.dayOfWeek,
        'dayOfYear': value.dayOfYear,
        'year': value.year,
        'dayOfMonth': value.dayOfMonth,
    };
}

/**
* @export
* @enum {string}
*/
export enum LocalDateMonthEnum {
    January = 'JANUARY',
    February = 'FEBRUARY',
    March = 'MARCH',
    April = 'APRIL',
    May = 'MAY',
    June = 'JUNE',
    July = 'JULY',
    August = 'AUGUST',
    September = 'SEPTEMBER',
    October = 'OCTOBER',
    November = 'NOVEMBER',
    December = 'DECEMBER'
}
/**
* @export
* @enum {string}
*/
export enum LocalDateDayOfWeekEnum {
    Monday = 'MONDAY',
    Tuesday = 'TUESDAY',
    Wednesday = 'WEDNESDAY',
    Thursday = 'THURSDAY',
    Friday = 'FRIDAY',
    Saturday = 'SATURDAY',
    Sunday = 'SUNDAY'
}


