// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GrantedAuthority,
    GrantedAuthorityFromJSON,
    GrantedAuthorityToJSON,
} from './index';

/**
 * Информация о пользователе
 * @export
 * @interface MercuryUserDetails
 */
export interface MercuryUserDetails  {
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    objectSid?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MercuryUserDetails
     */
    userNonExpired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MercuryUserDetails
     */
    userNonLocked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MercuryUserDetails
     */
    credentialsNonExpired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MercuryUserDetails
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof MercuryUserDetails
     */
    roles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    departmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    fullName?: string;
    /**
     * 
     * @type {Array<GrantedAuthority>}
     * @memberof MercuryUserDetails
     */
    authorities?: Array<GrantedAuthority>;
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof MercuryUserDetails
     */
    password?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MercuryUserDetails
     */
    admin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MercuryUserDetails
     */
    accountNonLocked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MercuryUserDetails
     */
    accountNonExpired?: boolean;
}

export function MercuryUserDetailsFromJSON(json: any): MercuryUserDetails {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'objectSid': !exists(json, 'objectSid') ? undefined : json['objectSid'],
        'userNonExpired': !exists(json, 'userNonExpired') ? undefined : json['userNonExpired'],
        'userNonLocked': !exists(json, 'userNonLocked') ? undefined : json['userNonLocked'],
        'credentialsNonExpired': !exists(json, 'credentialsNonExpired') ? undefined : json['credentialsNonExpired'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
        'departmentId': !exists(json, 'departmentId') ? undefined : json['departmentId'],
        'fullName': !exists(json, 'fullName') ? undefined : json['fullName'],
        'authorities': !exists(json, 'authorities') ? undefined : (json['authorities'] as Array<any>).map(GrantedAuthorityFromJSON),
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'admin': !exists(json, 'admin') ? undefined : json['admin'],
        'accountNonLocked': !exists(json, 'accountNonLocked') ? undefined : json['accountNonLocked'],
        'accountNonExpired': !exists(json, 'accountNonExpired') ? undefined : json['accountNonExpired'],
    };
}

export function MercuryUserDetailsToJSON(value?: MercuryUserDetails): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'email': value.email,
        'userName': value.userName,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'objectSid': value.objectSid,
        'userNonExpired': value.userNonExpired,
        'userNonLocked': value.userNonLocked,
        'credentialsNonExpired': value.credentialsNonExpired,
        'enabled': value.enabled,
        'roles': value.roles,
        'departmentId': value.departmentId,
        'fullName': value.fullName,
        'authorities': value.authorities === undefined ? undefined : (value.authorities as Array<any>).map(GrantedAuthorityToJSON),
        'username': value.username,
        'password': value.password,
        'admin': value.admin,
        'accountNonLocked': value.accountNonLocked,
        'accountNonExpired': value.accountNonExpired,
    };
}


