// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Информация о результате
 * @export
 * @interface Meta
 */
export interface Meta  {
    /**
     * Общее количество записей
     * @type {number}
     * @memberof Meta
     */
    total?: number;
    /**
     * Номер первой записи в списке
     * @type {number}
     * @memberof Meta
     */
    start?: number;
    /**
     * Размер страницы
     * @type {number}
     * @memberof Meta
     */
    pageSize?: number;
}

export function MetaFromJSON(json: any): Meta {
    return {
        'total': !exists(json, 'total') ? undefined : json['total'],
        'start': !exists(json, 'start') ? undefined : json['start'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
    };
}

export function MetaToJSON(value?: Meta): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'total': value.total,
        'start': value.start,
        'pageSize': value.pageSize,
    };
}


