// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelApiResponse
 */
export interface ModelApiResponse  {
    /**
     * 
     * @type {number}
     * @memberof ModelApiResponse
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelApiResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApiResponse
     */
    comment?: string;
    /**
     * 
     * @type {object}
     * @memberof ModelApiResponse
     */
    data?: object;
}

export function ModelApiResponseFromJSON(json: any): ModelApiResponse {
    return {
        'status': !exists(json, 'status') ? undefined : json['status'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function ModelApiResponseToJSON(value?: ModelApiResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'status': value.status,
        'message': value.message,
        'comment': value.comment,
        'data': value.data,
    };
}


