// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Параметр проекта анкеты
 * @export
 * @interface ProjectParameter
 */
export interface ProjectParameter  {
    /**
     * Уникальный идентификатор
     * @type {string}
     * @memberof ProjectParameter
     */
    id: string;
    /**
     * Название параметра
     * @type {string}
     * @memberof ProjectParameter
     */
    name: string;
    /**
     * Значение параметра
     * @type {string}
     * @memberof ProjectParameter
     */
    value: string;
}

export function ProjectParameterFromJSON(json: any): ProjectParameter {
    return {
        'id': json['id'],
        'name': json['name'],
        'value': json['value'],
    };
}

export function ProjectParameterToJSON(value?: ProjectParameter): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'value': value.value,
    };
}


