// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Вариант ответа
 * @export
 * @interface ProjectChoice
 */
export interface ProjectChoice  {
    /**
     * Уникальный идентификатор
     * @type {string}
     * @memberof ProjectChoice
     */
    id: string;
    /**
     * Название варианта ответа
     * @type {string}
     * @memberof ProjectChoice
     */
    name?: string;
    /**
     * Значение варианта ответа
     * @type {string}
     * @memberof ProjectChoice
     */
    value?: string;
    /**
     * Комментарий
     * @type {string}
     * @memberof ProjectChoice
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectChoice
     */
    media?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectChoice
     */
    hide?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectChoice
     */
    answerGroupTags?: string;
    /**
     * Флаги
     * @type {Array<string>}
     * @memberof ProjectChoice
     */
    flags?: Array<ProjectChoiceFlagsEnum>;
}

export function ProjectChoiceFromJSON(json: any): ProjectChoice {
    return {
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'media': !exists(json, 'media') ? undefined : json['media'],
        'hide': !exists(json, 'hide') ? undefined : json['hide'],
        'answerGroupTags': !exists(json, 'answerGroupTags') ? undefined : json['answerGroupTags'],
        'flags': !exists(json, 'flags') ? undefined : json['flags'],
    };
}

export function ProjectChoiceToJSON(value?: ProjectChoice): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'value': value.value,
        'comment': value.comment,
        'media': value.media,
        'hide': value.hide,
        'answerGroupTags': value.answerGroupTags,
        'flags': value.flags,
    };
}

/**
* @export
* @enum {string}
*/
export enum ProjectChoiceFlagsEnum {
    AddOpenAnswer = 'ADD_OPEN_ANSWER',
    SingleChoice = 'SINGLE_CHOICE',
    NonRotatable = 'NON_ROTATABLE',
    DoNotRead = 'DO_NOT_READ'
}


