// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Meta,
    MetaFromJSON,
    MetaToJSON,
    Project,
    ProjectFromJSON,
    ProjectToJSON,
} from './index';

/**
 * Список проектов анкет
 * @export
 * @interface ProjectsList
 */
export interface ProjectsList  {
    /**
     * 
     * @type {Meta}
     * @memberof ProjectsList
     */
    meta?: Meta;
    /**
     * Результат
     * @type {Array<Project>}
     * @memberof ProjectsList
     */
    data?: Array<Project>;
}

export function ProjectsListFromJSON(json: any): ProjectsList {
    return {
        'meta': !exists(json, 'meta') ? undefined : MetaFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(ProjectFromJSON),
    };
}

export function ProjectsListToJSON(value?: ProjectsList): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'meta': MetaToJSON(value.meta),
        'data': value.data === undefined ? undefined : (value.data as Array<any>).map(ProjectToJSON),
    };
}


