// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ProjectTableRow
 * @export
 * @interface ProjectTableRow
 */
export interface ProjectTableRow  {
    /**
     * Уникальный идентификатор
     * @type {string}
     * @memberof ProjectTableRow
     */
    id?: string;
    /**
     * Название
     * @type {string}
     * @memberof ProjectTableRow
     */
    name?: string;
    /**
     * Комментарий
     * @type {string}
     * @memberof ProjectTableRow
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectTableRow
     */
    media?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectTableRow
     */
    hide?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectTableRow
     */
    notRotate?: boolean;
}

export function ProjectTableRowFromJSON(json: any): ProjectTableRow {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'media': !exists(json, 'media') ? undefined : json['media'],
        'hide': !exists(json, 'hide') ? undefined : json['hide'],
        'notRotate': !exists(json, 'notRotate') ? undefined : json['notRotate'],
    };
}

export function ProjectTableRowToJSON(value?: ProjectTableRow): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'comment': value.comment,
        'media': value.media,
        'hide': value.hide,
        'notRotate': value.notRotate,
    };
}


