// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Meta,
    MetaFromJSON,
    MetaToJSON,
    Question,
    QuestionFromJSON,
    QuestionToJSON,
} from './index';

/**
 * Список вопросов
 * @export
 * @interface QuestionsList
 */
export interface QuestionsList  {
    /**
     * 
     * @type {Meta}
     * @memberof QuestionsList
     */
    meta?: Meta;
    /**
     * Результат
     * @type {Array<Question>}
     * @memberof QuestionsList
     */
    data?: Array<Question>;
}

export function QuestionsListFromJSON(json: any): QuestionsList {
    return {
        'meta': !exists(json, 'meta') ? undefined : MetaFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(QuestionFromJSON),
    };
}

export function QuestionsListToJSON(value?: QuestionsList): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'meta': MetaToJSON(value.meta),
        'data': value.data === undefined ? undefined : (value.data as Array<any>).map(QuestionToJSON),
    };
}


