// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Квота
 * @export
 * @interface Quota
 */
export interface Quota  {
    /**
     * Уникальный идентификатор
     * @type {string}
     * @memberof Quota
     */
    id: string;
    /**
     * Условие
     * @type {string}
     * @memberof Quota
     */
    condition: string;
    /**
     * Количество
     * @type {number}
     * @memberof Quota
     */
    count: number;
}

export function QuotaFromJSON(json: any): Quota {
    return {
        'id': json['id'],
        'condition': json['condition'],
        'count': json['count'],
    };
}

export function QuotaToJSON(value?: Quota): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'condition': value.condition,
        'count': value.count,
    };
}


