// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Регион
 * @export
 * @interface Region
 */
export interface Region  {
    /**
     * Уникальный идентификатор
     * @type {string}
     * @memberof Region
     */
    id?: string;
    /**
     * Название региона
     * @type {string}
     * @memberof Region
     */
    name?: string;
    /**
     * Аббревиатура региона
     * @type {string}
     * @memberof Region
     */
    abbr?: string;
    /**
     * 
     * @type {Region}
     * @memberof Region
     */
    parent?: Region;
}

export function RegionFromJSON(json: any): Region {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'abbr': !exists(json, 'abbr') ? undefined : json['abbr'],
        'parent': !exists(json, 'parent') ? undefined : RegionFromJSON(json['parent']),
    };
}

export function RegionToJSON(value?: Region): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'abbr': value.abbr,
        'parent': RegionToJSON(value.parent),
    };
}


