// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Роль
 * @export
 * @interface Role
 */
export interface Role  {
    /**
     * Уникальный идентификатор
     * @type {number}
     * @memberof Role
     */
    id?: number;
    /**
     * Код роли
     * @type {string}
     * @memberof Role
     */
    code?: string;
    /**
     * Название роли
     * @type {string}
     * @memberof Role
     */
    name?: string;
    /**
     * Описание роли
     * @type {string}
     * @memberof Role
     */
    description?: string;
}

export function RoleFromJSON(json: any): Role {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function RoleToJSON(value?: Role): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'description': value.description,
    };
}


