// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleVO
 */
export interface RoleVO  {
    /**
     * 
     * @type {number}
     * @memberof RoleVO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RoleVO
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleVO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleVO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleVO
     */
    authority?: string;
}

export function RoleVOFromJSON(json: any): RoleVO {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'authority': !exists(json, 'authority') ? undefined : json['authority'],
    };
}

export function RoleVOToJSON(value?: RoleVO): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'description': value.description,
        'authority': value.authority,
    };
}


