// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Запрос на задание прав доступа
 * @export
 * @interface SetPermissionRequest
 */
export interface SetPermissionRequest  {
    /**
     * Идентификатор пользователя или группы в ActiveDirectory
     * @type {string}
     * @memberof SetPermissionRequest
     */
    objectSid: string;
    /**
     * Права доступа
     * @type {number}
     * @memberof SetPermissionRequest
     */
    permission: number;
}

export function SetPermissionRequestFromJSON(json: any): SetPermissionRequest {
    return {
        'objectSid': json['objectSid'],
        'permission': json['permission'],
    };
}

export function SetPermissionRequestToJSON(value?: SetPermissionRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'objectSid': value.objectSid,
        'permission': value.permission,
    };
}


