// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Настройка
 * @export
 * @interface Setting
 */
export interface Setting  {
    /**
     * Уникальный идентификатор
     * @type {string}
     * @memberof Setting
     */
    id?: string;
    /**
     * Название настройки
     * @type {string}
     * @memberof Setting
     */
    name?: string;
    /**
     * Описание настройки
     * @type {string}
     * @memberof Setting
     */
    description?: string;
    /**
     * Тип настройки
     * @type {string}
     * @memberof Setting
     */
    type?: SettingTypeEnum;
    /**
     * Значение настройки
     * @type {string}
     * @memberof Setting
     */
    value?: string;
}

export function SettingFromJSON(json: any): Setting {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function SettingToJSON(value?: Setting): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'type': value.type,
        'value': value.value,
    };
}

/**
* @export
* @enum {string}
*/
export enum SettingTypeEnum {
    Int = 'INT',
    Float = 'FLOAT',
    String = 'STRING',
    Date = 'DATE'
}


