// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Department,
    DepartmentFromJSON,
    DepartmentToJSON,
    Instant,
    InstantFromJSON,
    InstantToJSON,
} from './index';

/**
 * Блок шаблонов вопросов
 * @export
 * @interface TemplateBlock
 */
export interface TemplateBlock  {
    /**
     * Уникальный идентификатор
     * @type {string}
     * @memberof TemplateBlock
     */
    id?: string;
    /**
     * Название блока шаблонов вопросов
     * @type {string}
     * @memberof TemplateBlock
     */
    name?: string;
    /**
     * Идентификатор родительского блока шаблонов вопросов
     * @type {string}
     * @memberof TemplateBlock
     */
    parentId?: string;
    /**
     * 
     * @type {Department}
     * @memberof TemplateBlock
     */
    department?: Department;
    /**
     * 
     * @type {Instant}
     * @memberof TemplateBlock
     */
    updatedTime?: Instant;
    /**
     * 
     * @type {Instant}
     * @memberof TemplateBlock
     */
    createdTime?: Instant;
}

export function TemplateBlockFromJSON(json: any): TemplateBlock {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'department': !exists(json, 'department') ? undefined : DepartmentFromJSON(json['department']),
        'updatedTime': !exists(json, 'updatedTime') ? undefined : InstantFromJSON(json['updatedTime']),
        'createdTime': !exists(json, 'createdTime') ? undefined : InstantFromJSON(json['createdTime']),
    };
}

export function TemplateBlockToJSON(value?: TemplateBlock): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'parentId': value.parentId,
        'department': DepartmentToJSON(value.department),
        'updatedTime': InstantToJSON(value.updatedTime),
        'createdTime': InstantToJSON(value.createdTime),
    };
}


