// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Meta,
    MetaFromJSON,
    MetaToJSON,
    TemplateQuestion,
    TemplateQuestionFromJSON,
    TemplateQuestionToJSON,
} from './index';

/**
 * Список шаблонов вопросов
 * @export
 * @interface TemplateQuestionsList
 */
export interface TemplateQuestionsList  {
    /**
     * 
     * @type {Meta}
     * @memberof TemplateQuestionsList
     */
    meta?: Meta;
    /**
     * Результат
     * @type {Array<TemplateQuestion>}
     * @memberof TemplateQuestionsList
     */
    data?: Array<TemplateQuestion>;
}

export function TemplateQuestionsListFromJSON(json: any): TemplateQuestionsList {
    return {
        'meta': !exists(json, 'meta') ? undefined : MetaFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(TemplateQuestionFromJSON),
    };
}

export function TemplateQuestionsListToJSON(value?: TemplateQuestionsList): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'meta': MetaToJSON(value.meta),
        'data': value.data === undefined ? undefined : (value.data as Array<any>).map(TemplateQuestionToJSON),
    };
}


