// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSidRequest
 */
export interface UpdateSidRequest  {
    /**
     * 
     * @type {string}
     * @memberof UpdateSidRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSidRequest
     */
    password?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSidRequest
     */
    apply?: boolean;
}

export function UpdateSidRequestFromJSON(json: any): UpdateSidRequest {
    return {
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'apply': !exists(json, 'apply') ? undefined : json['apply'],
    };
}

export function UpdateSidRequestToJSON(value?: UpdateSidRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'username': value.username,
        'password': value.password,
        'apply': value.apply,
    };
}


